name: Release multiple devices

on:
  schedule:
    - cron:  '0 3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Checking if a new version was released at all before starting the matrix would be more efficient, but depends on device
  # So run the whole matrix as cron. One of the first checks is if there is a need for release at all.
  build-devices:
    strategy:
      matrix:
        include:
          - device-id: caiman # Pixel 9 Pro
            magisk-preinit-device: sda10
#          - device-id: oriole # Pixel 6
#            magisk-preinit-device: metadata
#          - device-id: tokay # Pixel 9
#            magisk-preinit-device: sda10
#          - device-id: husky # Pixel 8 Pro
#            magisk-preinit-device: sda10
#          - device-id: shiba # Pixel 8
#            magisk-preinit-device: sda10
#          - device-id: bluejay # Pixel 6a
#            magisk-preinit-device: sda8
          # - device-id: cheetah # Pixel Pro 7 
          #  magisk-preinit-device: persist # https://xdaforums.com/t/guide-to-lock-bootloader-while-using-rooted-otaos-magisk-root.4510295/page-5#post-88499289)
    uses: ./.github/workflows/release-single.yaml
    secrets: inherit 
    with:
      device-id: ${{ matrix.device-id }}
      magisk-preinit-device: ${{ matrix.magisk-preinit-device }}
