name: Renovate
on:
  schedule:
    - cron: '0 20 * * *'
  
  workflow_dispatch:
  
  # Rebase open PRs on push
  push:
    branches: [ main ]
    
  pull_request:
    types: [synchronize, opened, reopened]
    paths:
      - .github/workflows/renovate.yaml
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@822441559e94f98b67b82d97ab89fe3003b0a247 # v44.2.0
        with:
          configurationFile: .github/renovate.json5
          # https://docs.renovatebot.com/modules/platform/github/#running-using-a-fine-grained-token
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
            RENOVATE_REPOSITORIES: ${{ github.repository }}
            LOG_LEVEL: ${{ inputs.logLevel || 'debug' }}
